# Generated by Django 5.0.2 on 2024-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
