# Generated by Django 5.0.3 on 2024-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_todo_data_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
