# Generated by Django 5.0.3 on 2024-03-28 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='subject',
        ),
        migrations.AddField(
            model_name='todo',
            name='bio',
            field=models.TextField(default='hello'),
        ),
        migrations.AddField(
            model_name='todo',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='adarsh', max_length=250),
        ),
        migrations.AddField(
            model_name='todo',
            name='salary',
            field=models.IntegerField(default=15000),
        ),
    ]
