# Generated by Django 5.0.3 on 2024-03-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_todo_bio_alter_todo_dob_alter_todo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='bio',
            field=models.CharField(max_length=250),
        ),
    ]
