# Generated by Django 5.0.3 on 2024-03-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_todo_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='bio',
            field=models.TextField(),
        ),
    ]
