# Generated by Django 5.0.3 on 2024-03-28 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_todo_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
